import SideBar from "@/app/_components/sidebar/SideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-screen flex gap-4 items-center ">
      <aside className="bg-green-50 sm:w-[190px]">
        <SideBar />
      </aside>
      <div className="px-4 py-1 w-full ">{children}</div>
    </main>
  );
}
